title: KPHP — a PHP compiler
lang: en
description: KPHP compiles a limited subset of PHP, making it run faster than plain PHP

theme: jekyll-rtd-theme
edit: false

url_github_kphp: https://github.com/VKCOM/kphp
url_github_kphp_polyfills: https://github.com/VKCOM/kphp-polyfills
url_github_kphp_snippets: https://github.com/VKCOM/kphp-snippets
url_github_kphp_tools: https://github.com/VKCOM/kphp-tools
url_github_issues: https://github.com/VKCOM/kphp/issues
url_github_nocolor: https://github.com/VKCOM/nocolor
url_github_nocc: https://github.com/VKCOM/nocc
url_telegram_chat: https://t.me/kphp_chat
url_functions_txt: https://github.com/VKCOM/kphp/blob/master/builtin-functions/_functions.txt
url_PDO: https://github.com/VKCOM/kphp/blob/master/builtin-functions/PDO/PDO.php
url_dockerfile: https://github.com/VKCOM/kphp/blob/master/Dockerfile
url_license_file: https://github.com/VKCOM/kphp/blob/master/LICENSE
url_vertex_desc_json: https://github.com/VKCOM/kphp/blob/master/compiler/vertex-desc.json
url_website_kphp: https://vkcom.github.io/kphp/
url_website_kphpstorm: https://vkcom.github.io/kphpstorm/
url_package_curl: https://github.com/VKCOM/curl/tree/dpkg-build-7.60.0
url_package_h3: https://github.com/VKCOM/uber-h3/tree/dpkg-build
url_package_epoll_shim: https://github.com/VKCOM/epoll-shim/tree/osx-platform
url_package_timelib: https://github.com/VKCOM/timelib/tree/master
url_package_h3_mac: https://github.com/uber/h3/tree/stable-3.x

copyright:
  revision: false
author: LLC «V Kontakte»
github_metadata: false

addons: []

readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - .idea

plugins: []
