name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
  HOMEBREW_NO_INSTALL_FROM_API: ""

jobs:
  build-macos:
    runs-on: ${{matrix.os}}-15
    strategy:
      matrix:
        include:
          - os: macos
            compiler: clang++
            cpp: 17
          - os: macos
            compiler: clang++
            cpp: 20

    name: "${{matrix.os}} / ${{matrix.compiler}} / c++${{matrix.cpp}}"

    steps:
      - uses: actions/checkout@v4

      # because of https://github.com/orgs/Homebrew/discussions/4612
      - name: Check Environment
        run: |
          export HOMEBREW_NO_INSTALL_FROM_API=
          brew untap --force homebrew/cask

      - name: Setup Environment
        run: |
          brew tap shivammathur/php
          brew update
          brew install python@3.13 re2c coreutils libiconv googletest shivammathur/php/php@7.4
          brew link --overwrite --force shivammathur/php/php@7.4
          brew link --overwrite --force python@3.13
          /opt/homebrew/opt/python@3.13/libexec/bin/python -m pip install --upgrade pip --user --break-system-packages && /opt/homebrew/opt/python@3.13/libexec/bin/pip install --break-system-packages jsonschema six cmake==3.31.6

      - name: Run cmake
        run: |
          cmake -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
                -DCMAKE_CXX_STANDARD=${{matrix.cpp}} \
                -DDOWNLOAD_MISSING_LIBRARIES=On \
                -DPython3_EXECUTABLE=/opt/homebrew/opt/python@3.13/libexec/bin/python \
                -S $GITHUB_WORKSPACE \
                -B ${{runner.workspace}}/build

      - name: Build all
        run: make -C ${{runner.workspace}}/build -j$(nproc) all

      - name: Run unit tests
        run: make -C ${{runner.workspace}}/build -j$(nproc) test

      - name: Compile dummy PHP script
        working-directory: ${{runner.workspace}}/build
        run: |
          echo 'hello world' > demo.php 
          $GITHUB_WORKSPACE/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} demo.php
          kphp_out/server -o
